---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpmyadmin
  namespace: apps
spec:
  chart:
    spec:
      chart: phpmyadmin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 1m0s
  values:
    db:
      host:
        mysqldb