---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysqldb
  namespace: apps
spec:
  chart:
    spec:
      chart: mysql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: flux-system
  interval: 1m0s
  values:
    architecture: replication
    auth:
      replicationPassword: "iridacio"
      rootPassword: "nZjrSKJvTb" # for migration purposes
      password: "Arus7qQISM"
    primary:
      extraVolumeMounts:
          - name:  mysql-pv-storage
            mountPath: "/data/"
      extraVolumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
    secondary:
      replicaCount: 2