apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: apps
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/workspaces/flux-demo/test_db"