---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentd-helmrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: fluentd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 1m0s
