---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: monitoring
spec:
  chart:
    spec:
      chart: tigera-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  interval: 10m0s