---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  chart:
    spec:
      chart: elasticsearch
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 10m0s
  values:
    antiAffinity: "soft"
    esJavaOpts: "-Xmx128m -Xms128m"
    volumeClaimTemplate:
      storageCalssName: "standard"
      resources:
        requests:
          storage: 3Gi