---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluent-bit
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 10m0s
  values:
    service:
      annotations:
        prometheus.io/path: "/api/v1/metrics/prometheus"
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush {{ .Values.flush }}
            Log_Level {{ .Values.logLevel }}
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port {{ .Values.metricsPort }}
            Health_Check On

      ## https://docs.fluentbit.io/manual/pipeline/inputs
      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On

        [INPUT]
            Name systemd
            Tag host.*
            Systemd_Filter _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail On

      ## https://docs.fluentbit.io/manual/pipeline/filters
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

      ## https://docs.fluentbit.io/manual/pipeline/outputs
      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            HTTP_User fluent
            HTTP_Passwd fluent123
            Host elasticsearch-master
            Logstash_Format On
            Retry_Limit False
            tls On 
            tls.verify Off
            Suppress_Type_Name On 
            Trace_Error On

        [OUTPUT]
            Name es
            Match host.*
            HTTP_User fluent 
            HTTP_Passwd fluent123
            Host elasticsearch-master
            Logstash_Format On
            Logstash_Prefix node
            Retry_Limit False
            tls On 
            tls.verify Off
            Suppress_Type_Name On 
            Trace_Error On

      ## https://docs.fluentbit.io/manual/pipeline/parsers
      customParsers: |
        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
