---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentd
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluentd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 10m0s
  values:
    env:
      - name: "K8S_NODE_NAME"
        value: "minikube"
      - name: FLUENT_ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password