---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentd
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluentd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 10m0s
