---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kibana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: elastic
  interval: 10m0s
