apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
