---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-elastic-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-elasticsearch-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m0s
