---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  timeout: 1m0s
  url: https://helm.elastic.co
