---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  timeout: 1m0s
  url: https://fluent.github.io/helm-charts